export const BLANK_STRING = "";
export const NOTE_MAX_LENGTH = 200;
export const LOAD_MORE_ELEMENTS = "...";
export const DEBOUNCING_TIME = 300;
export const SUBMIT_BUTTON_TEXT = "Submit";
export const COLON = ":";
export const DOT = ".";
export const EMPTY_ARRAY = [];
export const DOLLAR_SIGN = "$";
export const BLANK_SPACE = " ";
export const QUESTION_MARK = "?";
export const EQUAL_SIGN = "=";
