export const FIRST_NAME_PLACEHOLDER = "John";
export const NICKNAME_PLACEHOLDER = "Johnny";
export const LAST_NAME_PLACEHOLDER = "Doe";
export const EMAIL_PLACEHOLDER = "john.doe@domain.com";
export const PASSWORD_PLACEHOLDER = "********";
export const NOTE_PLACEHOLDER = "John Doe is the employee of the month.";
export const EMERGENCY_CONTACT_NAME_PLACEHOLDER = "Mary";
export const EMERGENCY_CONTACT_RELATIONSHIP_PLACEHOLDER = "Wife";
export const EMERGENCY_CONTACT_PHONE_PLACEHOLDER = "+1 (123) 456-7890";
